server:
  port: 9001
  tomcat:
    connection-timeout: 5s
    threads:
      max: 100
      min-spare: 10

spring:
  application:
    name: catalog-service
  config.import: "optional:configserver:http://config-service:8888"
  cloud:
    config:
      request-connect-timeout: 1000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://polar-postgres-catalog:5432/polardb_catalog
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      pool-name: polardb-pool
  jpa:
    hibernate.ddl-auto: validate

management.endpoints.web.exposure.include: refresh